export interface tableType {
 id: string,
 border: boolean,
 showHeaderOverflow: boolean,
 showOverflow: boolean,
 height:number,
 columns:Array<object>,
 rowConfig:{keyField:string,isHover:boolean},
 columnConfig: { resizable:{ type:boolean, default: true}},
 customConfig: {storage:{type:boolean,default:false}, checkMethod:{type:any}},
 printConfig: {columns:{type:Array<object>}},
 sortConfig: {defaultSort:{type:object|Array<object>,default:{field:"id",} },orders:{},remote:{type:boolean,default:true},multiple:{type:boolean,default:undefined}},
 filterConfig: {},
 pagerConfig: {enabled:{type:boolean,default:true},pageSize:{type:number,default:10},pageSizes:{type:Array<number>,default:[10,50,100]}},
 formConfig: {},
 toolbarConfig: {buttons:{type:Array<object>|undefined},refresh?:{type:boolean,default:true},import?:{type:boolean,default:true},export:{type:boolean,default:true},zoom:{type:boolean,default:true}},
 proxyConfig: {ajax:{query:{type:()=>{}}},delete:{},save:{} },
 importConfig: {remote:{type:boolean,default:true},types:{type:string[],default:["xlsx"]}},
 exportConfig: {remote:{type:boolean,default:true},types:{type:string[],default:["xlsx"]},modes?:{type:string[]}},
 checkboxConfig: {labelField?:{type:string},reserve?:{type:boolean},highlight?:{type:boolean},range?:{type:boolean}},
 editRules: object,
 editConfig: object,
}